FROM node:20-alpine AS base

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/api/package.json apps/api/package.json
COPY packages ./packages
RUN npm install

COPY apps/api ./apps/api
WORKDIR /app/apps/api

RUN npx prisma generate --schema=prisma/schema.prisma
RUN npm run build

EXPOSE 4000
CMD ["npm", "run", "start"]
